import type { NextPage } from 'next'
import Head from 'next/head'
import Task, { TaskEvent } from '../components/Task'

const tasks = [
  {
    id: 1,
    name: 'Task 1',
    completed: false,
    subtasks: [
      {
        id: 2,
        name: 'Subtask 1',
        completed: false,
        subtasks: [
          {
            id: 3,
            name: 'Deep Task 1',
            completed: false,
            subtasks: [],
          },
        ],
      },
      {
        id: 4,
        name: 'Subtask 2',
        completed: true,
        subtasks: [],
      },
    ],
  },
  {
    id: 5,
    name: 'Task 2',
    completed: true,
    subtasks: [],
  },
]

const Home: NextPage = () => {
  const onComplete = ({ id, completed }: TaskEvent) => {
    console.log(id, completed)
  }

  return (
    <div className="max-w-md mx-auto">
      <Head>
        <title>Hello Next</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Hello Next</h1>
      {tasks.map(x => (
        <Task key={x.id} {...x} onChange={onComplete} />
      ))}
    </div>
  )
}

export default Home
