import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div className="max-w-md mx-auto">
      <Head>
        <title>Hello Next</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Hello Next</h1>
    </div>
  )
}

export default Home
